[package]
name = "fsae-wireless-test"
version = "0.1.0"
edition = "2021"

[dependencies]
rumqttc = "0.24.0"
rumqttd = "0.19.0"
tracing-subscriber = "0.3.19"
config = "0.15.7"
clap = "4.5.27"
tokio = { version = "1.43.0", features = ["full"] }
