[package]
name = "fsae-wireless-test"
version = "0.1.0"
edition = "2021"

[dependencies]
rumqttc = "0.24"
rumqttd = "0.19"
tracing-subscriber = "0.3"
config = "0.15"
clap = "4.5.29"
tokio = { version = "1.43", features = ["full"] }
