name: Clippy check

on:
  push:
    paths-ignore:
      - 'fsae-vehicle-fw/**'
  pull_request:
    paths-ignore:
      - 'fsae-vehicle-fw/**'

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
